CREATE TABLE "site_settings" (
	"id" text PRIMARY KEY NOT NULL,
	"model_name" text NOT NULL,
	"base_en" text,
	"base_de" text,
	"bio_en" text,
	"bio_de" text,
	"height" text,
	"bust" text,
	"waist" text,
	"hips" text,
	"shoe_size" text,
	"hair_en" text,
	"hair_de" text,
	"eyes_en" text,
	"eyes_de" text,
	"additional_detail_en" text,
	"additional_detail_de" text,
	"agency_name" text,
	"agency_location_en" text,
	"agency_location_de" text,
	"agency_url" text,
	"agency_booking_email" text,
	"emphasize_agency" boolean DEFAULT false NOT NULL,
	"public_email" text,
	"contact_label_en" text,
	"contact_label_de" text,
	"additional_contact_label_en" text,
	"additional_contact_label_de" text,
	"additional_contact_value" text,
	"additional_contact_url" text,
	"email_clickable" boolean DEFAULT false NOT NULL,
	"instagram_handle" text,
	"instagram_url" text,
	"instagram_in_footer" boolean DEFAULT true NOT NULL,
	"languages_en" text,
	"languages_de" text,
	"base_cities_en" text,
	"base_cities_de" text,
	"selected_clients_en" text,
	"selected_clients_de" text,
	"portrait_url" text NOT NULL,
	"portrait_storage_path" text,
	"portrait_original_filename" text,
	"portrait_content_type" text,
	"portrait_file_size" integer,
	"portrait_blob_etag" text,
	"portrait_width" integer NOT NULL,
	"portrait_height" integer NOT NULL,
	"portrait_alt_en" text NOT NULL,
	"portrait_alt_de" text,
	"portrait_photographer" text,
	"portrait_credit" text,
	"comp_card_enabled" boolean DEFAULT false NOT NULL,
	"comp_card_url" text,
	"comp_card_storage_path" text,
	"comp_card_original_filename" text,
	"comp_card_content_type" text,
	"comp_card_file_size" integer,
	"comp_card_blob_etag" text,
	"year_statement_en" text,
	"year_statement_de" text,
	"revision" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "site_settings_primary_check" CHECK ("site_settings"."id" = 'primary'),
	CONSTRAINT "site_settings_model_name_check" CHECK (length(trim("site_settings"."model_name")) > 0),
	CONSTRAINT "site_settings_portrait_width_check" CHECK ("site_settings"."portrait_width" > 0),
	CONSTRAINT "site_settings_portrait_height_check" CHECK ("site_settings"."portrait_height" > 0),
	CONSTRAINT "site_settings_portrait_alt_en_check" CHECK (length(trim("site_settings"."portrait_alt_en")) > 0),
	CONSTRAINT "site_settings_portrait_file_size_check" CHECK ("site_settings"."portrait_file_size" is null or "site_settings"."portrait_file_size" > 0),
	CONSTRAINT "site_settings_comp_card_file_size_check" CHECK ("site_settings"."comp_card_file_size" is null or "site_settings"."comp_card_file_size" > 0),
	CONSTRAINT "site_settings_revision_check" CHECK ("site_settings"."revision" >= 0)
);
--> statement-breakpoint
WITH "initial_portrait" AS (
	SELECT
		"photos"."url",
		"photos"."storage_path",
		"photos"."original_filename",
		"photos"."content_type",
		"photos"."file_size",
		"photos"."blob_etag",
		"photos"."width",
		"photos"."height"
	FROM "photos"
	INNER JOIN "shootings" ON "shootings"."id" = "photos"."shooting_id"
	WHERE "shootings"."slug" = 'studio-portraits'
		AND "photos"."original_filename" = 'studio-portraits-08.jpg'
	LIMIT 1
)
INSERT INTO "site_settings" (
	"id",
	"model_name",
	"base_en",
	"base_de",
	"bio_en",
	"bio_de",
	"contact_label_en",
	"contact_label_de",
	"instagram_handle",
	"instagram_url",
	"instagram_in_footer",
	"portrait_url",
	"portrait_storage_path",
	"portrait_original_filename",
	"portrait_content_type",
	"portrait_file_size",
	"portrait_blob_etag",
	"portrait_width",
	"portrait_height",
	"portrait_alt_en",
	"portrait_alt_de",
	"year_statement_en",
	"year_statement_de"
)
SELECT
	'primary',
	'Zoe Schmidt',
	'Wiehl / Germany',
	'Wiehl / Deutschland',
	'Zoe Schmidt is a model based in Wiehl, Germany. Her portfolio brings together professional studio work and natural portraits shaped by quiet moments, light, and place.',
	'Zoe Schmidt ist ein Model aus Wiehl. Ihr Portfolio verbindet professionelle Studioarbeiten mit natürlichen Porträts, geprägt von ruhigen Momenten, Licht und besonderen Orten.',
	'CONTACT',
	'KONTAKT',
	'@zoe.schmidt',
	'https://www.instagram.com/zoe.schmidt/',
	true,
	coalesce("initial_portrait"."url", '/media/profile/studio-portraits-08.jpg'),
	"initial_portrait"."storage_path",
	coalesce("initial_portrait"."original_filename", 'studio-portraits-08.jpg'),
	coalesce("initial_portrait"."content_type", 'image/jpeg'),
	"initial_portrait"."file_size",
	"initial_portrait"."blob_etag",
	coalesce("initial_portrait"."width", 1536),
	coalesce("initial_portrait"."height", 2304),
	'Studio portrait of Zoe Schmidt with wet hair, looking over her shoulder.',
	'Studioporträt von Zoe Schmidt mit nassem Haar und Blick über die Schulter.',
	'A growing study of presence, movement and the quiet character of light — collected through portraits made in the studio and outside it.',
	'Eine wachsende Studie über Präsenz, Bewegung und den stillen Charakter des Lichts – gesammelt in Porträts aus dem Studio und darüber hinaus.'
FROM (VALUES (1)) AS "seed" ("value")
LEFT JOIN "initial_portrait" ON true
ON CONFLICT ("id") DO NOTHING;
